#!/usr/bin/env python

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt


def plot_cdf(fn, label):
    xs = list()
    ys = list()
    fd = open(fn, 'r')
    count = str(cdf2count[fn])
    if cdf2count[fn] > 10**6:
        count = '%dK' % int(cdf2count[fn]/(10**3))
    if cdf2count[fn] > 10**9:
        count = '%dM' % int(cdf2count[fn]/(10**6))
    if cdf2count[fn] > 10**12:
        count = '%dG' % int(cdf2count[fn]/(10**9))
    # label = '%s [%s]' % (label, count)

    for line in fd:
        x, y = line.split()
        xs.append(float(x))
        ys.append(float(y))
    plt.step(xs, ys, label=label, where='post')


def read_counts():
    cdf2count = dict()
    fd = open('cdf-counts.txt')
    for line in fd:
        name, count = line.split()
        cdf2count[name] = int(float(count))
    fd.close()
    return cdf2count

cdf2count = read_counts()

# RTT P50

plt.xlabel("AS Path Length Difference [Peer - Transit]", fontsize=16)
plt.ylabel("Cumulative Fraction of Prefixes", fontsize=16)
plt.xlim(-5, +5)
plt.ylim(0, 1)
# plt.xscale('log')
# plt.yscale('log')
plt.grid()
# plt.tight_layout()
# plt.locator_params(axis='x', nbins=6)
# plt.locator_params(axis='y', nticks=6)
# plt.xticks(x, xticks)
plot_cdf('data/peers-transit-smpl500-rtt_ms_p50-aspathlendiff.cdf', 'All prefixes')
plot_cdf('data/peers-lose-transit-smpl500-rtt_ms_p50-aspathlendiff.cdf', 'Peers worse than transit')
plot_cdf('data/peers-lose20-transit-smpl500-rtt_ms_p50-aspathlendiff.cdf', 'Peers worse than transit by 20ms')
# plot_cdf('data/peers-lose20-transit-smpl500-rtt_ms_p50-uniqlendiff.cdf', 'Peers worse than Transit by 20ms, removing prepending')
plt.legend(loc="best")
plt.savefig('rtt-p50-aslendiff-worse.pdf')

plt.clf()

plt.xlabel("AS Path Length Difference [Peer - Transit]", fontsize=16)
plt.ylabel("Cumulative Fraction of Traffic", fontsize=16)
plt.xlim(-5, +5)
plt.ylim(0, 1)
# plt.xscale('log')
# plt.yscale('log')
plt.grid()
# plt.tight_layout()
# plt.locator_params(axis='x', nbins=6)
# plt.locator_params(axis='y', nticks=6)
# plt.xticks(x, xticks)
plot_cdf('data/peers-transit-smpl500-rtt_ms_p50-aspathlendiff-weight.cdf', 'Peers vs Transit')
plot_cdf('data/peers-lose-transit-smpl500-rtt_ms_p50-aspathlendiff-weight.cdf', 'Peers worse than Transit')
plot_cdf('data/peers-lose20-transit-smpl500-rtt_ms_p50-aspathlendiff-weight.cdf', 'Peers worse than Transit by 20ms')
plot_cdf('data/peers-lose20-transit-smpl500-rtt_ms_p50-uniqlendiff-weight.cdf', 'Peers worse than Transit by 20ms, removing prepending')
plt.legend(loc="best")
plt.savefig('rtt-p50-aslendiff-worse-weight.pdf')

plt.clf()

plt.xlabel("AS Path Length Difference [Peer - Transit]", fontsize=16)
plt.ylabel("Cumulative Fraction of Prefixes", fontsize=16)
plt.xlim(-5, +5)
plt.ylim(0, 1)
# plt.xscale('log')
# plt.yscale('log')
plt.grid()
# plt.tight_layout()
# plt.locator_params(axis='x', nbins=6)
# plt.locator_params(axis='y', nticks=6)
# plt.xticks(x, xticks)
plot_cdf('data/peers-transit-smpl500-rtt_ms_p50-aspathlendiff.cdf', 'Peers vs Transit')
plot_cdf('data/peers-win-transit-smpl500-rtt_ms_p50-aspathlendiff.cdf', 'Peers better than Transit')
plot_cdf('data/peers-win20-transit-smpl500-rtt_ms_p50-aspathlendiff.cdf', 'Peers better than Transit by 20ms')
plot_cdf('data/peers-win20-transit-smpl500-rtt_ms_p50-uniqlendiff.cdf', 'Peers better than Transit by 20ms, removing prepending')
plt.legend(loc="best")
plt.savefig('rtt-p50-aslendiff-better.pdf')

plt.clf()

plt.xlabel("AS Path Length Difference [Peer - Transit]", fontsize=16)
plt.ylabel("Cumulative Fraction of Traffic", fontsize=16)
plt.xlim(-5, +5)
plt.ylim(0, 1)
# plt.xscale('log')
# plt.yscale('log')
plt.grid()
# plt.tight_layout()
# plt.locator_params(axis='x', nbins=6)
# plt.locator_params(axis='y', nticks=6)
# plt.xticks(x, xticks)
plot_cdf('data/peers-transit-smpl500-rtt_ms_p50-aspathlendiff-weight.cdf', 'Peers vs Transit')
plot_cdf('data/peers-win-transit-smpl500-rtt_ms_p50-aspathlendiff-weight.cdf', 'Peers better than Transit')
plot_cdf('data/peers-win20-transit-smpl500-rtt_ms_p50-aspathlendiff-weight.cdf', 'Peers better than Transit by 20ms')
plot_cdf('data/peers-win20-transit-smpl500-rtt_ms_p50-uniqlendiff-weight.cdf', 'Peers better than Transit by 20ms, removing prepending')
plt.legend(loc="best")
plt.savefig('rtt-p50-aslendiff-better-weight.pdf')

plt.clf()

### RTT P95

plt.xlabel("AS Path Length Difference [Peer - Transit]", fontsize=16)
plt.ylabel("Cumulative Fraction of Prefixes", fontsize=16)
plt.xlim(-5, +5)
plt.ylim(0, 1)
# plt.xscale('log')
# plt.yscale('log')
plt.grid()
# plt.tight_layout()
# plt.locator_params(axis='x', nbins=6)
# plt.locator_params(axis='y', nticks=6)
# plt.xticks(x, xticks)
plot_cdf('data/peers-transit-smpl500-rtt_ms_p95-aspathlendiff.cdf', 'Peers vs Transit')
plot_cdf('data/peers-lose-transit-smpl500-rtt_ms_p95-aspathlendiff.cdf', 'Peers worse than Transit')
plot_cdf('data/peers-lose60-transit-smpl500-rtt_ms_p95-aspathlendiff.cdf', 'Peers worse than Transit by 60ms')
plot_cdf('data/peers-lose60-transit-smpl500-rtt_ms_p95-uniqlendiff.cdf', 'Peers worse than Transit by 60ms, removing prepending')
plt.legend(loc="best")
plt.savefig('rtt-p95-aslendiff-worse.pdf')

plt.clf()

plt.xlabel("AS Path Length Difference [Peer - Transit]", fontsize=16)
plt.ylabel("Cumulative Fraction of Traffic", fontsize=16)
plt.xlim(-5, +5)
plt.ylim(0, 1)
# plt.xscale('log')
# plt.yscale('log')
plt.grid()
# plt.tight_layout()
# plt.locator_params(axis='x', nbins=6)
# plt.locator_params(axis='y', nticks=6)
# plt.xticks(x, xticks)
plot_cdf('data/peers-transit-smpl500-rtt_ms_p95-aspathlendiff-weight.cdf', 'Peers vs Transit')
plot_cdf('data/peers-lose-transit-smpl500-rtt_ms_p95-aspathlendiff-weight.cdf', 'Peers worse than Transit')
plot_cdf('data/peers-lose60-transit-smpl500-rtt_ms_p95-aspathlendiff-weight.cdf', 'Peers worse than Transit by 60ms')
plot_cdf('data/peers-lose60-transit-smpl500-rtt_ms_p95-uniqlendiff-weight.cdf', 'Peers worse than Transit by 60ms, removing prepending')
plt.legend(loc="best")
plt.savefig('rtt-p95-aslendiff-worse-weight.pdf')

plt.clf()

plt.xlabel("AS Path Length Difference [Peer - Transit]", fontsize=16)
plt.ylabel("Cumulative Fraction of Prefixes", fontsize=16)
plt.xlim(-5, +5)
plt.ylim(0, 1)
# plt.xscale('log')
# plt.yscale('log')
plt.grid()
# plt.tight_layout()
# plt.locator_params(axis='x', nbins=6)
# plt.locator_params(axis='y', nticks=6)
# plt.xticks(x, xticks)
plot_cdf('data/peers-transit-smpl500-rtt_ms_p95-aspathlendiff.cdf', 'Peers vs Transit')
plot_cdf('data/peers-win-transit-smpl500-rtt_ms_p95-aspathlendiff.cdf', 'Peers better than Transit')
plot_cdf('data/peers-win60-transit-smpl500-rtt_ms_p95-aspathlendiff.cdf', 'Peers better than Transit by 60ms')
plot_cdf('data/peers-win60-transit-smpl500-rtt_ms_p95-uniqlendiff.cdf', 'Peers better than Transit by 60ms, removing prepending')
plt.legend(loc="best")
plt.savefig('rtt-p95-aslendiff-better.pdf')

plt.clf()

plt.xlabel("AS Path Length Difference [Peer - Transit]", fontsize=16)
plt.ylabel("Cumulative Fraction of Traffic", fontsize=16)
plt.xlim(-5, +5)
plt.ylim(0, 1)
# plt.xscale('log')
# plt.yscale('log')
plt.grid()
# plt.tight_layout()
# plt.locator_params(axis='x', nbins=6)
# plt.locator_params(axis='y', nticks=6)
# plt.xticks(x, xticks)
plot_cdf('data/peers-transit-smpl500-rtt_ms_p95-aspathlendiff-weight.cdf', 'Peers vs Transit')
plot_cdf('data/peers-win-transit-smpl500-rtt_ms_p95-aspathlendiff-weight.cdf', 'Peers better than Transit')
plot_cdf('data/peers-win60-transit-smpl500-rtt_ms_p95-aspathlendiff-weight.cdf', 'Peers better than Transit by 60ms')
plot_cdf('data/peers-win60-transit-smpl500-rtt_ms_p95-uniqlendiff-weight.cdf', 'Peers better than Transit by 60ms, removing prepending')
plt.legend(loc="best")
plt.savefig('rtt-p95-aslendiff-better-weight.pdf')

plt.clf()

### HD FRAC

plt.xlabel("AS Path Length Difference [Peer - Transit]", fontsize=16)
plt.ylabel("Cumulative Fraction of Prefixes", fontsize=16)
plt.xlim(-5, +5)
plt.ylim(0, 1)
# plt.xscale('log')
# plt.yscale('log')
plt.grid()
# plt.tight_layout()
# plt.locator_params(axis='x', nbins=6)
# plt.locator_params(axis='y', nticks=6)
# plt.xticks(x, xticks)
plot_cdf('data/peers-transit-smpl500-hd_capable_frac-aspathlendiff.cdf', 'Peers vs Transit')
plot_cdf('data/peers-lose-transit-smpl500-hd_capable_frac-aspathlendiff.cdf', 'Peers worse than Transit')
plot_cdf('data/peers-lose10p-transit-smpl500-hd_capable_frac-aspathlendiff.cdf', 'Peers worse than Transit by 10%')
plot_cdf('data/peers-lose10p-transit-smpl500-hd_capable_frac-uniqlendiff.cdf', 'Peers worse than Transit by 10%, removing prepending')
plt.legend(loc="best")
plt.savefig('hdfrac-aslendiff-worse.pdf')

plt.clf()

plt.xlabel("AS Path Length Difference [Peer - Transit]", fontsize=16)
plt.ylabel("Cumulative Fraction of Traffic", fontsize=16)
plt.xlim(-5, +5)
plt.ylim(0, 1)
# plt.xscale('log')
# plt.yscale('log')
plt.grid()
# plt.tight_layout()
# plt.locator_params(axis='x', nbins=6)
# plt.locator_params(axis='y', nticks=6)
# plt.xticks(x, xticks)
plot_cdf('data/peers-transit-smpl500-hd_capable_frac-aspathlendiff-weight.cdf', 'Peers vs Transit')
plot_cdf('data/peers-lose-transit-smpl500-hd_capable_frac-aspathlendiff-weight.cdf', 'Peers worse than Transit')
plot_cdf('data/peers-lose10p-transit-smpl500-hd_capable_frac-aspathlendiff-weight.cdf', 'Peers worse than Transit by 10%')
plot_cdf('data/peers-lose10p-transit-smpl500-hd_capable_frac-uniqlendiff-weight.cdf', 'Peers worse than Transit by 10%, removing prepending')
plt.legend(loc="best")
plt.savefig('hdfrac-aslendiff-worse-weight.pdf')

plt.clf()

plt.xlabel("AS Path Length Difference [Peer - Transit]", fontsize=16)
plt.ylabel("Cumulative Fraction of Prefixes", fontsize=16)
plt.xlim(-5, +5)
plt.ylim(0, 1)
# plt.xscale('log')
# plt.yscale('log')
plt.grid()
# plt.tight_layout()
# plt.locator_params(axis='x', nbins=6)
# plt.locator_params(axis='y', nticks=6)
# plt.xticks(x, xticks)
plot_cdf('data/peers-transit-smpl500-hd_capable_frac-aspathlendiff.cdf', 'Peers vs Transit')
plot_cdf('data/peers-win-transit-smpl500-hd_capable_frac-aspathlendiff.cdf', 'Peers better than Transit')
plot_cdf('data/peers-win10p-transit-smpl500-hd_capable_frac-aspathlendiff.cdf', 'Peers better than Transit by 10%')
plot_cdf('data/peers-win10p-transit-smpl500-hd_capable_frac-uniqlendiff.cdf', 'Peers better than Transit by 10%, removing prepending')
plt.legend(loc="best")
plt.savefig('hdfrac-aslendiff-better.pdf')

plt.clf()

plt.xlabel("AS Path Length Difference [Peer - Transit]", fontsize=16)
plt.ylabel("Cumulative Fraction of Traffic", fontsize=16)
plt.xlim(-5, +5)
plt.ylim(0, 1)
# plt.xscale('log')
# plt.yscale('log')
plt.grid()
# plt.tight_layout()
# plt.locator_params(axis='x', nbins=6)
# plt.locator_params(axis='y', nticks=6)
# plt.xticks(x, xticks)
plot_cdf('data/peers-transit-smpl500-hd_capable_frac-aspathlendiff-weight.cdf', 'Peers vs Transit')
plot_cdf('data/peers-win-transit-smpl500-hd_capable_frac-aspathlendiff-weight.cdf', 'Peers better than Transit')
plot_cdf('data/peers-win10p-transit-smpl500-hd_capable_frac-aspathlendiff-weight.cdf', 'Peers better than Transit by 10%')
plot_cdf('data/peers-win10p-transit-smpl500-hd_capable_frac-uniqlendiff-weight.cdf', 'Peers better than Transit by 10%, removing prepending')
plt.legend(loc="best")
plt.savefig('hdfrac-aslendiff-better-weight.pdf')

