#!/usr/bin/env python

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt


def plot_cdf(fn, label):
    xs = list()
    ys = list()
    fd = open(fn, 'r')
    count = str(cdf2count[fn])
    if cdf2count[fn] > 10**6:
        count = '%dK' % int(cdf2count[fn]/(10**3))
    if cdf2count[fn] > 10**9:
        count = '%dM' % int(cdf2count[fn]/(10**6))
    if cdf2count[fn] > 10**12:
        count = '%dG' % int(cdf2count[fn]/(10**9))
    # label = '%s [%s]' % (label, count)

    for line in fd:
        x, y = line.split()
        xs.append(float(x))
        ys.append(float(y))
    plt.step(xs, ys, label=label, where='post')


def read_counts():
    cdf2count = dict()
    fd = open('cdf-counts.txt')
    for line in fd:
        name, count = line.split()
        cdf2count[name] = int(float(count))
    fd.close()
    return cdf2count

cdf2count = read_counts()

plt.xlabel("RTT Difference (ms) [Short - Long]", fontsize=16)
plt.ylabel("Cumulative Fraction of Prefixes", fontsize=16)
plt.xlim(-80, 80)
plt.ylim(0, 1)
# plt.xscale('log')
# plt.yscale('log')
plt.grid()
# plt.tight_layout()
# plt.locator_params(axis='x', nbins=6)
# plt.locator_params(axis='y', nticks=6)
# plt.xticks(x, xticks)
# plot_cdf('data/aspathlen-private,public,transit-private,public,transit-smpl500-rtt_ms_p50.cdf', 'All')
# plot_cdf('data/aspathlen-private,public,transit-private,public,transit-smpl500-rtt_ms_p50-0len.cdf', 'Same length')
plot_cdf('data/aspathlen-private,public,transit-private,public,transit-smpl500-rtt_ms_p50-1len.cdf', '1 AS difference')
plot_cdf('data/aspathlen-private,public,transit-private,public,transit-smpl500-rtt_ms_p50-2len.cdf', '2 AS difference')
plot_cdf('data/aspathlen-private,public,transit-private,public,transit-smpl500-rtt_ms_p50-3plus.cdf', '3+ AS difference')
# plot_cdf('data/aspathlen-private,public,transit-private,public,transit-smpl500-rtt_ms_p50-4plus.cdf', '4+ AS difference')
# plot_cdf('data/aspathlen-private,public,transit-private,public,transit-smpl500-rtt_ms_p50-noprep1len.cdf', '1 distinct ASes (ignore prepending)')
# plot_cdf('data/aspathlen-private,public,transit-private,public,transit-smpl500-rtt_ms_p50-noprep2len.cdf', '2 distinct ASes (ignore prepending)')
# plot_cdf('data/aspathlen-private,public,transit-private,public,transit-smpl500-rtt_ms_p50-noprep3mlen.cdf', '3+ distinct ASes (ignore prepending)')
plt.legend(loc="best")
plt.savefig('rtt-p50-aslen.pdf')

plt.clf()

plt.xlabel("RTT Difference (ms) [Short - Long]", fontsize=16)
plt.ylabel("Cumulative Fraction of Prefixes", fontsize=16)
plt.xlim(-80, 80)
plt.ylim(0, 1)
# plt.xscale('log')
# plt.yscale('log')
plt.grid()
# plt.tight_layout()
# plt.locator_params(axis='x', nbins=6)
# plt.locator_params(axis='y', nticks=6)
# plt.xticks(x, xticks)
# plot_cdf('data/aspathlen-private,public-private,public-smpl500-rtt_ms_p50.cdf', 'All PNI/PX paths')
# plot_cdf('data/aspathlen-private,public-private,public-smpl500-rtt_ms_p50-0len.cdf', 'Same length')
# plot_cdf('data/aspathlen-smpl500-rtt_ms_p50-noprep0len.cdf', 'Same length (ignore prepending)')
plot_cdf('data/aspathlen-private,public-private,public-smpl500-rtt_ms_p50-1len.cdf', '1 AS difference')
plot_cdf('data/aspathlen-private,public-private,public-smpl500-rtt_ms_p50-2len.cdf', '2 AS difference')
plot_cdf('data/aspathlen-private,public-private,public-smpl500-rtt_ms_p50-3plus.cdf', '3+ AS difference')
# plot_cdf('data/aspathlen-private,public-private,public-smpl500-rtt_ms_p50-4plus.cdf', '4+ AS difference')
# plot_cdf('data/aspathlen-private,public-private,public-smpl500-rtt_ms_p50-noprep1len.cdf', '1 distinct ASes')
# plot_cdf('data/aspathlen-private,public-private,public-smpl500-rtt_ms_p50-noprep2len.cdf', '2 distinct ASes')
# plot_cdf('data/aspathlen-private,public-private,public-smpl500-rtt_ms_p50-noprep3mlen.cdf', '3+ distinct ASes')
plt.legend(loc="best")
plt.savefig('rtt-p50-aslen-private-public.pdf')

plt.clf()

plt.xlabel("RTT Difference (ms) [Short - Long]", fontsize=16)
plt.ylabel("Cumulative Fraction of Prefixes", fontsize=16)
plt.xlim(-80, 80)
plt.ylim(0, 1)
# plt.xscale('log')
# plt.yscale('log')
plt.grid()
# plt.tight_layout()
# plt.locator_params(axis='x', nbins=6)
# plt.locator_params(axis='y', nticks=6)
# plt.xticks(x, xticks)
# plot_cdf('data/aspathlen-transit-transit-smpl500-rtt_ms_p50.cdf', 'All transit paths')
# plot_cdf('data/aspathlen-transit-transit-smpl500-rtt_ms_p50-0len.cdf', 'Same length')
# plot_cdf('data/aspathlen-smpl500-rtt_ms_p50-noprep0len.cdf', 'Same length (ignore prepending)')
plot_cdf('data/aspathlen-transit-transit-smpl500-rtt_ms_p50-1len.cdf', '1 AS difference')
plot_cdf('data/aspathlen-transit-transit-smpl500-rtt_ms_p50-2len.cdf', '2 AS difference')
plot_cdf('data/aspathlen-transit-transit-smpl500-rtt_ms_p50-3plus.cdf', '3+ AS difference')
# plot_cdf('data/aspathlen-transit-transit-smpl500-rtt_ms_p50-4plus.cdf', '4+ AS difference')
# plot_cdf('data/aspathlen-transit-transit-smpl500-rtt_ms_p50-noprep1len.cdf', '1 distinct ASes')
# plot_cdf('data/aspathlen-transit-transit-smpl500-rtt_ms_p50-noprep2len.cdf', '2 distinct ASes')
# plot_cdf('data/aspathlen-transit-transit-smpl500-rtt_ms_p50-noprep3mlen.cdf', '3+ distinct ASes')
plt.legend(loc="best")
plt.savefig('rtt-p50-aslen-transit-transit.pdf')

plt.clf()

plt.xlabel("RTT Difference (ms) [Peer - BestTransit]", fontsize=16)
plt.ylabel("Cumulative Fraction of Prefixes", fontsize=16)
plt.xlim(-80, 80)
plt.ylim(0, 1)
# plt.xscale('log')
# plt.yscale('log')
plt.grid()
# plt.tight_layout()
# plt.locator_params(axis='x', nbins=6)
# plt.locator_params(axis='y', nticks=6)
# plt.xticks(x, xticks)
# plot_cdf('data/aspathlen-transit-transit-smpl500-rtt_ms_p50.cdf', 'All transit paths')
# plot_cdf('data/aspathlen-transit-transit-smpl500-rtt_ms_p50-0len.cdf', 'Same length')
# plot_cdf('data/aspathlen-smpl500-rtt_ms_p50-noprep0len.cdf', 'Same length (ignore prepending)')
plot_cdf('data/peers-transit-smpl500-rtt_ms_p50-0len.cdf', 'Same AS path length')
plot_cdf('data/peers-transit-smpl500-rtt_ms_p50-long1.cdf', 'Peer is 1 AS longer')
plot_cdf('data/peers-transit-smpl500-rtt_ms_p50-long2.cdf', 'Peer is 2 ASes longer')
plot_cdf('data/peers-transit-smpl500-rtt_ms_p50-short1.cdf', 'Peer is 1 AS shorter')
plot_cdf('data/peers-transit-smpl500-rtt_ms_p50-short2.cdf', 'Peer is 2 ASes shorter')
plt.legend(loc="best")
plt.savefig('rtt-p50-aslendiff-peers-transit.pdf')

plt.clf()

plt.xlabel("RTT Difference (ms) [Peer - BestTransit, no prepending]", fontsize=16)
plt.ylabel("Cumulative Fraction of Traffic", fontsize=16)
plt.xlim(-80, 80)
plt.ylim(0, 1)
# plt.xscale('log')
# plt.yscale('log')
plt.grid()
# plt.tight_layout()
# plt.locator_params(axis='x', nbins=6)
# plt.locator_params(axis='y', nticks=6)
# plt.xticks(x, xticks)
plot_cdf('data/peers-transit-smpl500-rtt_ms_p50-0lennp.cdf', 'Same AS path length')
plot_cdf('data/peers-transit-smpl500-rtt_ms_p50-long1mnp.cdf', 'Peer is 1+ AS longer')
plot_cdf('data/peers-transit-smpl500-rtt_ms_p50-short1np.cdf', 'Peer is 1 AS shorter')
plot_cdf('data/peers-transit-smpl500-rtt_ms_p50-short2np.cdf', 'Peer is 2 ASes shorter')
plot_cdf('data/peers-transit-smpl500-rtt_ms_p50-short3mnp.cdf', 'Peer is 3+ ASes shorter')
plt.legend(loc="best")
plt.savefig('rtt-p50-aslendiff-noprep-peers-transit.pdf')

# WEIGHTED

plt.clf()

plt.xlabel("RTT Difference (ms) [Short - Long]", fontsize=16)
plt.ylabel("Cumulative Fraction of Traffic", fontsize=16)
plt.xlim(-80, 80)
plt.ylim(0, 1)
# plt.xscale('log')
# plt.yscale('log')
plt.grid()
# plt.tight_layout()
# plt.locator_params(axis='x', nbins=6)
# plt.locator_params(axis='y', nticks=6)
# plt.xticks(x, xticks)
# plot_cdf('data/aspathlen-private,public,transit-private,public,transit-smpl500-rtt_ms_p50-weight.cdf', 'All')
# plot_cdf('data/aspathlen-private,public,transit-private,public,transit-smpl500-rtt_ms_p50-0len-weight.cdf', 'Same length')
plot_cdf('data/aspathlen-private,public,transit-private,public,transit-smpl500-rtt_ms_p50-1len-weight.cdf', '1 AS difference')
plot_cdf('data/aspathlen-private,public,transit-private,public,transit-smpl500-rtt_ms_p50-2len-weight.cdf', '2 AS difference')
plot_cdf('data/aspathlen-private,public,transit-private,public,transit-smpl500-rtt_ms_p50-3plus-weight.cdf', '3+ AS difference')
# plot_cdf('data/aspathlen-private,public,transit-private,public,transit-smpl500-rtt_ms_p50-4plus-weight.cdf', '4+ AS difference')
# plot_cdf('data/aspathlen-private,public,transit-private,public,transit-smpl500-rtt_ms_p50-noprep1len-weight.cdf', '1 distinct ASes')
# plot_cdf('data/aspathlen-private,public,transit-private,public,transit-smpl500-rtt_ms_p50-noprep2len-weight.cdf', '2 distinct ASes')
# plot_cdf('data/aspathlen-private,public,transit-private,public,transit-smpl500-rtt_ms_p50-noprep3mlen-weight.cdf', '3+ distinct ASes')
plt.legend(loc="best")
plt.savefig('rtt-p50-aslen-weight.pdf')

plt.clf()

plt.xlabel("RTT Difference (ms) [Short - Long]", fontsize=16)
plt.ylabel("Cumulative Fraction of Traffic", fontsize=16)
plt.xlim(-80, 80)
plt.ylim(0, 1)
# plt.xscale('log')
# plt.yscale('log')
plt.grid()
# plt.tight_layout()
# plt.locator_params(axis='x', nbins=6)
# plt.locator_params(axis='y', nticks=6)
# plt.xticks(x, xticks)
# plot_cdf('data/aspathlen-private,public-private,public-smpl500-rtt_ms_p50-weight.cdf', 'All PNI/PX paths')
# plot_cdf('data/aspathlen-private,public-private,public-smpl500-rtt_ms_p50-0len-weight.cdf', 'Same length')
# plot_cdf('data/aspathlen-smpl500-rtt_ms_p50-noprep0len.cdf', 'Same length (ignore prepending)')
plot_cdf('data/aspathlen-private,public-private,public-smpl500-rtt_ms_p50-1len-weight.cdf', '1 AS difference')
plot_cdf('data/aspathlen-private,public-private,public-smpl500-rtt_ms_p50-2len-weight.cdf', '2 AS difference')
plot_cdf('data/aspathlen-private,public-private,public-smpl500-rtt_ms_p50-3plus-weight.cdf', '3+ AS difference')
# plot_cdf('data/aspathlen-private,public-private,public-smpl500-rtt_ms_p50-4plus-weight.cdf', '4+ AS difference')
# plot_cdf('data/aspathlen-private,public-private,public-smpl500-rtt_ms_p50-noprep1len-weight.cdf', '1 distinct ASes')
# plot_cdf('data/aspathlen-private,public-private,public-smpl500-rtt_ms_p50-noprep2len-weight.cdf', '2 distinct ASes')
# plot_cdf('data/aspathlen-private,public-private,public-smpl500-rtt_ms_p50-noprep3mlen-weight.cdf', '3+ distinct ASes')
plt.legend(loc="best")
plt.savefig('rtt-p50-aslen-private-public-weight.pdf')

plt.clf()

plt.xlabel("RTT Difference (ms) [Short - Long]", fontsize=16)
plt.ylabel("Cumulative Fraction of Traffic", fontsize=16)
plt.xlim(-80, 80)
plt.ylim(0, 1)
# plt.xscale('log')
# plt.yscale('log')
plt.grid()
# plt.tight_layout()
# plt.locator_params(axis='x', nbins=6)
# plt.locator_params(axis='y', nticks=6)
# plt.xticks(x, xticks)
# plot_cdf('data/aspathlen-transit-transit-smpl500-rtt_ms_p50-weight.cdf', 'All transit paths')
# plot_cdf('data/aspathlen-transit-transit-smpl500-rtt_ms_p50-0len-weight.cdf', 'Same length')
plot_cdf('data/aspathlen-transit-transit-smpl500-rtt_ms_p50-1len-weight.cdf', '1 AS difference')
plot_cdf('data/aspathlen-transit-transit-smpl500-rtt_ms_p50-2len-weight.cdf', '2 AS difference')
plot_cdf('data/aspathlen-transit-transit-smpl500-rtt_ms_p50-3plus-weight.cdf', '3+ AS difference')
# plot_cdf('data/aspathlen-transit-transit-smpl500-rtt_ms_p50-4plus-weight.cdf', '4+ AS difference')
# plot_cdf('data/aspathlen-transit-transit-smpl500-rtt_ms_p50-noprep1len-weight.cdf', '1 distinct ASes')
# plot_cdf('data/aspathlen-transit-transit-smpl500-rtt_ms_p50-noprep2len-weight.cdf', '2 distinct ASes')
# plot_cdf('data/aspathlen-transit-transit-smpl500-rtt_ms_p50-noprep3mlen-weight.cdf', '3+ distinct ASes')
plt.legend(loc="best")
plt.savefig('rtt-p50-aslen-transit-transit-weight.pdf')

plt.clf()

plt.xlabel("RTT Difference (ms) [Peer - BestTransit]", fontsize=16)
plt.ylabel("Cumulative Fraction of Traffic", fontsize=16)
plt.xlim(-80, 80)
plt.ylim(0, 1)
# plt.xscale('log')
# plt.yscale('log')
plt.grid()
# plt.tight_layout()
# plt.locator_params(axis='x', nbins=6)
# plt.locator_params(axis='y', nticks=6)
# plt.xticks(x, xticks)
plot_cdf('data/peers-transit-smpl500-rtt_ms_p50-0len-weight.cdf', 'Same AS path length')
plot_cdf('data/peers-transit-smpl500-rtt_ms_p50-long1-weight.cdf', 'Peer is 1 AS longer')
plot_cdf('data/peers-transit-smpl500-rtt_ms_p50-long2-weight.cdf', 'Peer is 2 ASes longer')
plot_cdf('data/peers-transit-smpl500-rtt_ms_p50-short1-weight.cdf', 'Peer is 1 AS shorter')
plot_cdf('data/peers-transit-smpl500-rtt_ms_p50-short2-weight.cdf', 'Peer is 2 ASes shorter')
plt.legend(loc="best")
plt.savefig('rtt-p50-aslendiff-peers-transit-weight.pdf')

plt.clf()

plt.xlabel("RTT Difference (ms) [Peer - BestTransit, no prepending]", fontsize=16)
plt.ylabel("Cumulative Fraction of Traffic", fontsize=16)
plt.xlim(-80, 80)
plt.ylim(0, 1)
# plt.xscale('log')
# plt.yscale('log')
plt.grid()
# plt.tight_layout()
# plt.locator_params(axis='x', nbins=6)
# plt.locator_params(axis='y', nticks=6)
# plt.xticks(x, xticks)
plot_cdf('data/peers-transit-smpl500-rtt_ms_p50-0lennp-weight.cdf', 'Same AS path length')
plot_cdf('data/peers-transit-smpl500-rtt_ms_p50-long1mnp-weight.cdf', 'Peer is 1+ AS longer')
plot_cdf('data/peers-transit-smpl500-rtt_ms_p50-short1np-weight.cdf', 'Peer is 1 AS shorter')
plot_cdf('data/peers-transit-smpl500-rtt_ms_p50-short2np-weight.cdf', 'Peer is 2 ASes shorter')
plot_cdf('data/peers-transit-smpl500-rtt_ms_p50-short3mnp-weight.cdf', 'Peer is 3+ ASes shorter')
plt.legend(loc="best")
plt.savefig('rtt-p50-aslendiff-noprep-peers-transit-weight.pdf')









