#!/usr/bin/env python

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt


def plot_cdf(fn, label):
    xs = list()
    ys = list()
    fd = open(fn, 'r')
    count = str(cdf2count[fn])
    if cdf2count[fn] > 10**6:
        count = '%dK' % int(cdf2count[fn]/(10**3))
    if cdf2count[fn] > 10**9:
        count = '%dM' % int(cdf2count[fn]/(10**6))
    if cdf2count[fn] > 10**12:
        count = '%dG' % int(cdf2count[fn]/(10**9))
    label = '%s [%s]' % (label, count)

    for line in fd:
        x, y = line.split()
        xs.append(float(x))
        ys.append(float(y))
    plt.step(xs, ys, label=label, where='post')


def read_counts():
    cdf2count = dict()
    fd = open('cdf-counts.txt')
    for line in fd:
        name, count = line.split()
        cdf2count[name] = int(float(count))
    fd.close()
    return cdf2count

cdf2count = read_counts()


plt.xlabel("HD capable difference (fraction of samples)", fontsize=16)
plt.ylabel("Cumulative Fraction of Prefixes", fontsize=16)
plt.xlim(-0.20, 0.20)
plt.ylim(0, 1)
# plt.xscale('log')
# plt.yscale('log')
plt.grid()
# plt.tight_layout()
# plt.locator_params(axis='x', nbins=6)
# plt.locator_params(axis='y', nticks=6)
# plt.xticks(x, xticks)
# plot_cdf('data/aspathlen-private,public,transit-private,public,transit-smpl500-hd_capable_frac.cdf', 'All')
# plot_cdf('data/aspathlen-private,public,transit-private,public,transit-smpl500-hd_capable_frac-0len.cdf', 'Same length')
plot_cdf('data/aspathlen-private,public,transit-private,public,transit-smpl500-hd_capable_frac-1len.cdf', '1 AS difference')
plot_cdf('data/aspathlen-private,public,transit-private,public,transit-smpl500-hd_capable_frac-2len.cdf', '2 AS difference')
plot_cdf('data/aspathlen-private,public,transit-private,public,transit-smpl500-hd_capable_frac-3plus.cdf', '3+ AS difference')
# plot_cdf('data/aspathlen-private,public,transit-private,public,transit-smpl500-hd_capable_frac-noprep1len.cdf', '1 distinct ASes (ignore prepending)')
# plot_cdf('data/aspathlen-private,public,transit-private,public,transit-smpl500-hd_capable_frac-noprep2len.cdf', '2 distinct ASes (ignore prepending)')
# plot_cdf('data/aspathlen-private,public,transit-private,public,transit-smpl500-hd_capable_frac-noprep3mlen.cdf', '3+ distinct ASes (ignore prepending)')
plt.legend(loc="best")
plt.savefig('hdfrac-aslen.pdf')

plt.clf()

plt.xlabel("HD capable difference (fraction of samples)", fontsize=16)
plt.ylabel("Cumulative Fraction of Prefixes", fontsize=16)
plt.xlim(-0.20, 0.20)
plt.ylim(0, 1)
# plt.xscale('log')
# plt.yscale('log')
plt.grid()
# plt.tight_layout()
# plt.locator_params(axis='x', nbins=6)
# plt.locator_params(axis='y', nticks=6)
# plt.xticks(x, xticks)
# plot_cdf('data/aspathlen-private,public-private,public-smpl500-hd_capable_frac.cdf', 'All PNI/PX paths')
# plot_cdf('data/aspathlen-private,public-private,public-smpl500-hd_capable_frac-0len.cdf', 'Same length')
plot_cdf('data/aspathlen-private,public-private,public-smpl500-hd_capable_frac-1len.cdf', '1 AS difference')
plot_cdf('data/aspathlen-private,public-private,public-smpl500-hd_capable_frac-2len.cdf', '2 AS difference')
plot_cdf('data/aspathlen-private,public-private,public-smpl500-hd_capable_frac-3plus.cdf', '3+ AS difference')
# plot_cdf('data/aspathlen-private,public-private,public-smpl500-hd_capable_frac-noprep1len.cdf', '1 distinct ASes (ignore prepending)')
# plot_cdf('data/aspathlen-private,public-private,public-smpl500-hd_capable_frac-noprep2len.cdf', '2 distinct ASes (ignore prepending)')
# plot_cdf('data/aspathlen-private,public-private,public-smpl500-hd_capable_frac-noprep3mlen.cdf', '3+ distinct ASes (ignore prepending)')
plt.legend(loc="best")
plt.savefig('hdfrac-aslen-peers.pdf')

plt.clf()

plt.xlabel("HD capable difference (fraction of samples)", fontsize=16)
plt.ylabel("Cumulative Fraction of Prefixes", fontsize=16)
plt.xlim(-0.20, 0.20)
plt.ylim(0, 1)
# plt.xscale('log')
# plt.yscale('log')
plt.grid()
# plt.tight_layout()
# plt.locator_params(axis='x', nbins=6)
# plt.locator_params(axis='y', nticks=6)
# plt.xticks(x, xticks)
# plot_cdf('data/aspathlen-transit-transit-smpl500-hd_capable_frac.cdf', 'All transit paths')
# plot_cdf('data/aspathlen-transit-transit-smpl500-hd_capable_frac-0len.cdf', 'Same length')
plot_cdf('data/aspathlen-transit-transit-smpl500-hd_capable_frac-1len.cdf', '1 AS difference')
plot_cdf('data/aspathlen-transit-transit-smpl500-hd_capable_frac-2len.cdf', '2 AS difference')
plot_cdf('data/aspathlen-transit-transit-smpl500-hd_capable_frac-3plus.cdf', '3+ AS difference')
# plot_cdf('data/aspathlen-transit-transit-smpl500-hd_capable_frac-noprep1len.cdf', '1 distinct ASes (ignore prepending)')
# plot_cdf('data/aspathlen-transit-transit-smpl500-hd_capable_frac-noprep2len.cdf', '2 distinct ASes (ignore prepending)')
# plot_cdf('data/aspathlen-transit-transit-smpl500-hd_capable_frac-noprep3mlen.cdf', '3+ distinct ASes (ignore prepending)')
plt.legend(loc="best")
plt.savefig('hdfrac-aslen-transit.pdf')

plt.clf()

# WEIGHTED

plt.xlabel("HD capable difference (fraction of samples)", fontsize=16)
plt.ylabel("Cumulative Fraction of Traffic", fontsize=16)
plt.xlim(-0.20, 0.20)
plt.ylim(0, 1)
# plt.xscale('log')
# plt.yscale('log')
plt.grid()
# plt.tight_layout()
# plt.locator_params(axis='x', nbins=6)
# plt.locator_params(axis='y', nticks=6)
# plt.xticks(x, xticks)
# plot_cdf('data/aspathlen-private,public,transit-private,public,transit-smpl500-hd_capable_frac-weight.cdf', 'All')
# plot_cdf('data/aspathlen-private,public,transit-private,public,transit-smpl500-hd_capable_frac-0len-weight.cdf', 'Same length')
# plot_cdf('data/aspathlen-smpl500-rtt_ms_p50-noprep0len.cdf', 'Same length (ignore prepending)')
plot_cdf('data/aspathlen-private,public,transit-private,public,transit-smpl500-hd_capable_frac-1len-weight.cdf', '1 AS difference')
plot_cdf('data/aspathlen-private,public,transit-private,public,transit-smpl500-hd_capable_frac-2len-weight.cdf', '2 AS difference')
plot_cdf('data/aspathlen-private,public,transit-private,public,transit-smpl500-hd_capable_frac-3plus-weight.cdf', '3+ AS difference')
# plot_cdf('data/aspathlen-private,public,transit-private,public,transit-smpl500-hd_capable_frac-noprep1len-weight.cdf', '1 distinct ASes')
# plot_cdf('data/aspathlen-private,public,transit-private,public,transit-smpl500-hd_capable_frac-noprep2len-weight.cdf', '2 distinct ASes')
# plot_cdf('data/aspathlen-private,public,transit-private,public,transit-smpl500-hd_capable_frac-noprep3mlen-weight.cdf', '3+ distinct ASes')
plt.legend(loc="best")
plt.savefig('hdfrac-aslen-weight.pdf')

plt.clf()

plt.xlabel("HD capable difference (fraction of samples)", fontsize=16)
plt.ylabel("Cumulative Fraction of Traffic", fontsize=16)
plt.xlim(-0.20, 0.20)
plt.ylim(0, 1)
# plt.xscale('log')
# plt.yscale('log')
plt.grid()
# plt.tight_layout()
# plt.locator_params(axis='x', nbins=6)
# plt.locator_params(axis='y', nticks=6)
# plt.xticks(x, xticks)
# plot_cdf('data/aspathlen-private,public-private,public-smpl500-hd_capable_frac-weight.cdf', 'All PNI/PX paths')
# plot_cdf('data/aspathlen-private,public-private,public-smpl500-hd_capable_frac-0len-weight.cdf', 'Same length')
# plot_cdf('data/aspathlen-smpl500-rtt_ms_p50-noprep0len.cdf', 'Same length (ignore prepending)')
plot_cdf('data/aspathlen-private,public-private,public-smpl500-hd_capable_frac-1len-weight.cdf', '1 AS difference')
plot_cdf('data/aspathlen-private,public-private,public-smpl500-hd_capable_frac-2len-weight.cdf', '2 AS difference')
plot_cdf('data/aspathlen-private,public-private,public-smpl500-hd_capable_frac-3plus-weight.cdf', '3+ AS difference')
# plot_cdf('data/aspathlen-private,public-private,public-smpl500-hd_capable_frac-noprep1len-weight.cdf', '1 distinct ASes')
# plot_cdf('data/aspathlen-private,public-private,public-smpl500-hd_capable_frac-noprep2len-weight.cdf', '2 distinct ASes')
# plot_cdf('data/aspathlen-private,public-private,public-smpl500-hd_capable_frac-noprep3mlen-weight.cdf', '3+ distinct ASes')
plt.legend(loc="best")
plt.savefig('hdfrac-aslen-peers-weight.pdf')

plt.clf()

plt.xlabel("HD capable difference (fraction of samples)", fontsize=16)
plt.ylabel("Cumulative Fraction of Traffic", fontsize=16)
plt.xlim(-0.20, 0.20)
plt.ylim(0, 1)
# plt.xscale('log')
# plt.yscale('log')
plt.grid()
# plt.tight_layout()
# plt.locator_params(axis='x', nbins=6)
# plt.locator_params(axis='y', nticks=6)
# plt.xticks(x, xticks)
# plot_cdf('data/aspathlen-transit-transit-smpl500-hd_capable_frac-weight.cdf', 'All transit paths')
# plot_cdf('data/aspathlen-transit-transit-smpl500-hd_capable_frac-0len-weight.cdf', 'Same length')
# plot_cdf('data/aspathlen-smpl500-rtt_ms_p50-noprep0len.cdf', 'Same length (ignore prepending)')
plot_cdf('data/aspathlen-transit-transit-smpl500-hd_capable_frac-1len-weight.cdf', '1 AS difference')
plot_cdf('data/aspathlen-transit-transit-smpl500-hd_capable_frac-2len-weight.cdf', '2 AS difference')
plot_cdf('data/aspathlen-transit-transit-smpl500-hd_capable_frac-3plus-weight.cdf', '3+ AS difference')
# plot_cdf('data/aspathlen-transit-transit-smpl500-hd_capable_frac-noprep1len-weight.cdf', '1 distinct ASes')
# plot_cdf('data/aspathlen-transit-transit-smpl500-hd_capable_frac-noprep2len-weight.cdf', '2 distinct ASes')
# plot_cdf('data/aspathlen-transit-transit-smpl500-hd_capable_frac-noprep3mlen-weight.cdf', '3+ distinct ASes')
plt.legend(loc="best")
plt.savefig('hdfrac-aslen-transit-weight.pdf')

